In [1]:
from pathlib import Path

import numpy as np
import pandas as pd


pasta_alertario = Path(
    "/home/noemi/atmoseer/data/alertario/pluviometricos_parquet"
)

arquivo_estacoes = Path(
    "/home/noemi/atmoseer/data/alertario/estacoes_alertario.csv"
)

arquivo_grade_radar = Path(
    "sumare_radar_latlon_grid.npz"
)

arquivo_saida = Path(
    "mapeamento_pixel_estacao_alertario.csv"
)

print("Pasta pluviométricos:", pasta_alertario)
print("Cadastro de estações:", arquivo_estacoes)
print("Grade do radar:", arquivo_grade_radar)

Pasta pluviométricos: /home/noemi/atmoseer/data/alertario/pluviometricos_parquet
Cadastro de estações: /home/noemi/atmoseer/data/alertario/estacoes_alertario.csv
Grade do radar: sumare_radar_latlon_grid.npz

In [3]:
stations_df = pd.read_csv(
    arquivo_estacoes
)

print("Colunas:")
print(stations_df.columns.tolist())

print("\nQuantidade de estações cadastradas:")
print(len(stations_df))

display(
    stations_df.head(40)
)

Colunas:
['estacao_id', 'estacao', 'latitude', 'longitude', 'cota_m', 'utm_x_sad69z23', 'utm_y_sad69z23', 'tem_meteorologica']

Quantidade de estações cadastradas:
33

,estacao_id,estacao,latitude,longitude,cota_m,utm_x_sad69z23,utm_y_sad69z23,tem_meteorologica
0,1,Vidigal,-22.99250,-43.23306,85,681138.532,7456241.298,True
1,2,Urca,-22.95583,-43.16667,90,688004.213,7460236.157,False
2,3,Rocinha,-22.98583,-43.24500,160,679831.802,7457041.035,False
3,4,Tijuca,-22.93194,-43.22167,340,682358.108,7462941.416,False
4,5,Santa Teresa,-22.93167,-43.19639,170,684951.792,7462971.838,False
5,6,Copacabana,-22.98639,-43.18944,90,685675.030,7456902.449,False
6,7,Grajaú,-22.92222,-43.26750,80,677639.269,7463809.403,False
7,8,Ilha do Governador,-22.81806,-43.21028,0,683708.659,7475959.609,False
8,9,Penha,-22.84444,-43.27528,111,677059.917,7472757.104,False
9,10,Madureira,-22.87333,-43.33889,45,670409.679,7469665.020,False
10,11,Irajá,-22.82694,-43.33694,20,670692.602,7474733.927,True
11,12,Bangu,-22.88028,-43.46583,15,657403.761,7468956.662,False
12,13,Piedade,-22.89182,-43.31005,50,673344.642,7467452.646,False
13,14,Jacarepaguá/Tanque,-22.91250,-43.36472,73,667541.219,7465482.186,False
14,15,Saúde,-22.89606,-43.18786,15,685875.072,7466833.239,False
15,16,Jardim Botânico,-22.97278,-43.22389,0,682133.530,7458453.116,True
16,17,Barra/Barrinha,-23.00849,-43.29965,7,674262.081,7454520.709,False
17,18,Jacarepaguá/Cidade de Deus,-22.94556,-43.36278,15,667928.198,7461632.847,False
18,19,Barra/Riocentro,-22.97721,-43.39155,0,664879.400,7458100.000,True
19,20,Guaratiba,-23.05028,-43.59472,0,643972.241,7450214.260,True
20,21,Est. Grajaú/Jacarepaguá,-22.92556,-43.31583,105,672722.551,7463726.025,False
21,22,Santa Cruz,-22.90944,-43.68444,15,634915.936,7465594.315,True
22,23,Grande Méier,-22.89056,-43.27806,25,676628.743,7467665.546,False
23,24,Anchieta,-22.82694,-43.40333,50,663886.431,7474809.856,False
24,25,Grota Funda,-23.01444,-43.52139,11,651526.394,7454108.412,False
25,26,Campo Grande,-22.90361,-43.56194,30,647538.728,7466493.819,False
26,27,Sepetiba,-22.96889,-43.71167,62,632068.601,7459406.612,False
27,28,Alto da Boa Vista,-22.96583,-43.27833,355,676494.085,7459222.483,True
28,29,Av. Brasil/Mendanha,-22.85694,-43.54111,30,649669.378,7471561.078,False
29,30,Recreio dos Bandeirantes,-23.01000,-43.44056,10,659816.802,7454514.151,False
30,31,Laranjeiras,-22.94056,-43.18750,60,685883.625,7462252.656,False
31,32,São Cristóvão,-22.89667,-43.22167,25,682404.960,7466817.174,True
32,33,Tijuca/Muda,-22.93278,-43.24333,31,680136.137,7462851.843,False

In [4]:
colunas_necessarias = [
    "estacao_id",
    "estacao",
    "latitude",
    "longitude",
]

colunas_ausentes = [
    coluna
    for coluna in colunas_necessarias
    if coluna not in stations_df.columns
]

if colunas_ausentes:
    raise ValueError(
        f"Colunas ausentes no cadastro: {colunas_ausentes}"
    )

stations_df = stations_df[
    colunas_necessarias
].copy()

stations_df["estacao_id"] = pd.to_numeric(
    stations_df["estacao_id"],
    errors="coerce",
)

stations_df["latitude"] = pd.to_numeric(
    stations_df["latitude"],
    errors="coerce",
)

stations_df["longitude"] = pd.to_numeric(
    stations_df["longitude"],
    errors="coerce",
)

estacoes_invalidas = stations_df[
    stations_df[
        [
            "estacao_id",
            "latitude",
            "longitude",
        ]
    ].isna().any(axis=1)
]

if not estacoes_invalidas.empty:
    print("Estações com identificador ou coordenadas inválidas:")
    display(estacoes_invalidas)

stations_df = (
    stations_df
    .dropna(
        subset=[
            "estacao_id",
            "latitude",
            "longitude",
        ]
    )
    .drop_duplicates(
        subset=["estacao_id"]
    )
    .copy()
)

stations_df["estacao_id"] = (
    stations_df["estacao_id"]
    .astype(int)
)

print(
    "Estações com coordenadas válidas:",
    len(stations_df),
)

display(stations_df)

Estações com coordenadas válidas: 33

    estacao_id                     estacao  latitude  longitude
0            1                     Vidigal -22.99250  -43.23306
1            2                        Urca -22.95583  -43.16667
2            3                     Rocinha -22.98583  -43.24500
3            4                      Tijuca -22.93194  -43.22167
4            5                Santa Teresa -22.93167  -43.19639
5            6                  Copacabana -22.98639  -43.18944
6            7                      Grajaú -22.92222  -43.26750
7            8          Ilha do Governador -22.81806  -43.21028
8            9                       Penha -22.84444  -43.27528
9           10                   Madureira -22.87333  -43.33889
10          11                       Irajá -22.82694  -43.33694
11          12                       Bangu -22.88028  -43.46583
12          13                     Piedade -22.89182  -43.31005
13          14          Jacarepaguá/Tanque -22.91250  -43.36472
14          15                       Saúde -22.89606  -43.18786
15          16             Jardim Botânico -22.97278  -43.22389
16          17              Barra/Barrinha -23.00849  -43.29965
17          18  Jacarepaguá/Cidade de Deus -22.94556  -43.36278
18          19             Barra/Riocentro -22.97721  -43.39155
19          20                   Guaratiba -23.05028  -43.59472
20          21     Est. Grajaú/Jacarepaguá -22.92556  -43.31583
21          22                  Santa Cruz -22.90944  -43.68444
22          23                Grande Méier -22.89056  -43.27806
23          24                    Anchieta -22.82694  -43.40333
24          25                 Grota Funda -23.01444  -43.52139
25          26                Campo Grande -22.90361  -43.56194
26          27                    Sepetiba -22.96889  -43.71167
27          28           Alto da Boa Vista -22.96583  -43.27833
28          29         Av. Brasil/Mendanha -22.85694  -43.54111
29          30    Recreio dos Bandeirantes -23.01000  -43.44056
30          31                 Laranjeiras -22.94056  -43.18750
31          32               São Cristóvão -22.89667  -43.22167
32          33                 Tijuca/Muda -22.93278  -43.24333

In [6]:
arquivos = sorted(
    pasta_alertario.glob("*.parquet")
)

print(
    "Quantidade de arquivos:",
    len(arquivos),
)

estacoes_encontradas = []

for i, arquivo in enumerate(
    arquivos,
    start=1,
):

    df = pd.read_parquet(
        arquivo,
        columns=[
            "estacao_id",
            "estacao",
        ],
    )

    estacoes_encontradas.append(
        df[
            [
                "estacao_id",
                "estacao",
            ]
        ].drop_duplicates()
    )

    if i % 50 == 0 or i == len(arquivos):
        print(
            f"Arquivos analisados: {i}/{len(arquivos)}"
        )

estacoes_parquet = (
    pd.concat(
        estacoes_encontradas,
        ignore_index=True,
    )
    .drop_duplicates()
    .sort_values("estacao_id")
    .reset_index(drop=True)
)

print(
    "\nEstações presentes nos arquivos pluviométricos:",
    len(estacoes_parquet),
)

display(estacoes_parquet)

Quantidade de arquivos: 471
Arquivos analisados: 50/471
Arquivos analisados: 100/471
Arquivos analisados: 150/471
Arquivos analisados: 200/471
Arquivos analisados: 250/471
Arquivos analisados: 300/471
Arquivos analisados: 350/471
Arquivos analisados: 400/471
Arquivos analisados: 450/471
Arquivos analisados: 471/471

Estações presentes nos arquivos pluviométricos: 39

    estacao_id                     estacao
0            1                     Vidigal
1            2                        Urca
2            3                     Rocinha
3            4                      Tijuca
4            5                Santa Teresa
5            6                  Copacabana
6            7                      Grajaú
7            8          Ilha do Governador
8            9                       Penha
9           10                   Madureira
10          11                       Irajá
11          12                       Bangu
12          13                     Piedade
13          14          Jacarepaguá/Tanque
14          15                       Saúde
15          16             Jardim Botânico
16          17              Barra/Barrinha
17          18  Jacarepaguá/Cidade de Deus
18          19             Barra/Riocentro
19          20                   Guaratiba
20          21     Est. Grajaú/Jacarepaguá
21          22                  Santa Cruz
22          23                Grande Méier
23          24                    Anchieta
24          25                 Grota Funda
25          26                Campo Grande
26          27                    Sepetiba
27          28           Alto da Boa Vista
28          29         Av. Brasil/Mendanha
29          30    Recreio dos Bandeirantes
30          31                 Laranjeiras
31          32               São Cristóvão
32          33                 Tijuca/Muda
33          34                      Sumaré
34         100                       Teste
35         101                    Mendanha
36         102                    Gericinó
37         103                      Sumaré
38         104             Barra/Itanhangá

In [7]:
ids_cadastro = set(
    stations_df["estacao_id"]
)

ids_parquet = set(
    estacoes_parquet["estacao_id"]
)

print(
    "Estações no cadastro:",
    len(ids_cadastro),
)

print(
    "Estações nos arquivos Parquet:",
    len(ids_parquet),
)

print(
    "Estações presentes nos dois:",
    len(
        ids_cadastro & ids_parquet
    ),
)

print(
    "IDs no cadastro, mas sem dados pluviométricos:",
    sorted(
        ids_cadastro - ids_parquet
    ),
)

print(
    "IDs com dados pluviométricos, mas sem cadastro:",
    sorted(
        ids_parquet - ids_cadastro
    ),
)

stations_df = stations_df[
    stations_df["estacao_id"].isin(
        ids_parquet
    )
].copy()

print(
    "\nEstações que serão mapeadas:",
    len(stations_df),
)

display(stations_df)

Estações no cadastro: 33
Estações nos arquivos Parquet: 39
Estações presentes nos dois: 33
IDs no cadastro, mas sem dados pluviométricos: []
IDs com dados pluviométricos, mas sem cadastro: [34, 100, 101, 102, 103, 104]

Estações que serão mapeadas: 33

    estacao_id                     estacao  latitude  longitude
0            1                     Vidigal -22.99250  -43.23306
1            2                        Urca -22.95583  -43.16667
2            3                     Rocinha -22.98583  -43.24500
3            4                      Tijuca -22.93194  -43.22167
4            5                Santa Teresa -22.93167  -43.19639
5            6                  Copacabana -22.98639  -43.18944
6            7                      Grajaú -22.92222  -43.26750
7            8          Ilha do Governador -22.81806  -43.21028
8            9                       Penha -22.84444  -43.27528
9           10                   Madureira -22.87333  -43.33889
10          11                       Irajá -22.82694  -43.33694
11          12                       Bangu -22.88028  -43.46583
12          13                     Piedade -22.89182  -43.31005
13          14          Jacarepaguá/Tanque -22.91250  -43.36472
14          15                       Saúde -22.89606  -43.18786
15          16             Jardim Botânico -22.97278  -43.22389
16          17              Barra/Barrinha -23.00849  -43.29965
17          18  Jacarepaguá/Cidade de Deus -22.94556  -43.36278
18          19             Barra/Riocentro -22.97721  -43.39155
19          20                   Guaratiba -23.05028  -43.59472
20          21     Est. Grajaú/Jacarepaguá -22.92556  -43.31583
21          22                  Santa Cruz -22.90944  -43.68444
22          23                Grande Méier -22.89056  -43.27806
23          24                    Anchieta -22.82694  -43.40333
24          25                 Grota Funda -23.01444  -43.52139
25          26                Campo Grande -22.90361  -43.56194
26          27                    Sepetiba -22.96889  -43.71167
27          28           Alto da Boa Vista -22.96583  -43.27833
28          29         Av. Brasil/Mendanha -22.85694  -43.54111
29          30    Recreio dos Bandeirantes -23.01000  -43.44056
30          31                 Laranjeiras -22.94056  -43.18750
31          32               São Cristóvão -22.89667  -43.22167
32          33                 Tijuca/Muda -22.93278  -43.24333

In [8]:
grid = np.load(
    arquivo_grade_radar
)

lat_grid = grid["lat"]
lon_grid = grid["lon"]

print(
    "Shape da grade de latitude:",
    lat_grid.shape,
)

print(
    "Shape da grade de longitude:",
    lon_grid.shape,
)

if lat_grid.shape != lon_grid.shape:
    raise ValueError(
        "As grades de latitude e longitude "
        "possuem dimensões diferentes."
    )

Shape da grade de latitude: (654, 656)
Shape da grade de longitude: (654, 656)

In [10]:
mapping = []

for _, row in stations_df.iterrows():

    station_id = row["estacao_id"]

    station_name = row["estacao"]

    station_lat = row["latitude"]

    station_lon = row["longitude"]

    # Distância da estação para cada pixel da grade.
    dist = (
        (lat_grid - station_lat) ** 2
        + (lon_grid - station_lon) ** 2
    )

    # Posição do pixel mais próximo.
    pixel_i, pixel_j = np.unravel_index(
        np.nanargmin(dist),
        dist.shape,
    )

    mapping.append(
        {
            "station_id": int(station_id),
            "nome": station_name,
            "latitude": float(station_lat),
            "longitude": float(station_lon),
            "pixel_i": int(pixel_i),
            "pixel_j": int(pixel_j),
        }
    )

mapping_df = (
    pd.DataFrame(mapping)
    .sort_values("station_id")
    .reset_index(drop=True)
)

print(
    "Quantidade de estações mapeadas:",
    len(mapping_df),
)

Quantidade de estações mapeadas: 33

In [11]:
mapping_df.to_csv(
    arquivo_saida,
    index=False,
)

print(
    "Arquivo salvo em:",
    arquivo_saida.resolve(),
)

print(
    "Quantidade de estações:",
    len(mapping_df),
)

display(
    mapping_df.head(40)
)

Arquivo salvo em: /home/noemi/atmoseer/notebooks/sumare_radar/mapeamento_pixel_estacao_alertario.csv
Quantidade de estações: 33

,station_id,nome,latitude,longitude,pixel_i,pixel_j
0,1,Vidigal,-22.99250,-43.23306,336,331
1,2,Urca,-22.95583,-43.16667,327,347
2,3,Rocinha,-22.98583,-43.24500,334,328
3,4,Tijuca,-22.93194,-43.22167,320,334
4,5,Santa Teresa,-22.93167,-43.19639,320,340
5,6,Copacabana,-22.98639,-43.18944,335,342
6,7,Grajaú,-22.92222,-43.26750,318,323
7,8,Ilha do Governador,-22.81806,-43.21028,291,337
8,9,Penha,-22.84444,-43.27528,298,321
9,10,Madureira,-22.87333,-43.33889,305,306
10,11,Irajá,-22.82694,-43.33694,293,306
11,12,Bangu,-22.88028,-43.46583,307,275
12,13,Piedade,-22.89182,-43.31005,310,313
13,14,Jacarepaguá/Tanque,-22.91250,-43.36472,315,299
14,15,Saúde,-22.89606,-43.18786,311,342
15,16,Jardim Botânico,-22.97278,-43.22389,331,333
16,17,Barra/Barrinha,-23.00849,-43.29965,340,315
17,18,Jacarepaguá/Cidade de Deus,-22.94556,-43.36278,324,300
18,19,Barra/Riocentro,-22.97721,-43.39155,332,293
19,20,Guaratiba,-23.05028,-43.59472,351,244
20,21,Est. Grajaú/Jacarepaguá,-22.92556,-43.31583,319,311
21,22,Santa Cruz,-22.90944,-43.68444,315,222
22,23,Grande Méier,-22.89056,-43.27806,310,320
23,24,Anchieta,-22.82694,-43.40333,293,290
24,25,Grota Funda,-23.01444,-43.52139,342,261
25,26,Campo Grande,-22.90361,-43.56194,313,252
26,27,Sepetiba,-22.96889,-43.71167,330,215
27,28,Alto da Boa Vista,-22.96583,-43.27833,329,320
28,29,Av. Brasil/Mendanha,-22.85694,-43.54111,301,257
29,30,Recreio dos Bandeirantes,-23.01000,-43.44056,341,281
30,31,Laranjeiras,-22.94056,-43.18750,323,342
31,32,São Cristóvão,-22.89667,-43.22167,311,334
32,33,Tijuca/Muda,-22.93278,-43.24333,321,329